/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silabsoft.runeagent.gui;

import java.awt.Component;
import java.awt.Desktop;
import java.net.URL;
import java.sql.Timestamp;
import javax.swing.DefaultListModel;
import org.silabsoft.runeagent.RuneAgent;
import org.silabsoft.runeagent.event.RuneAgentEvent;
import org.silabsoft.runeagent.event.RuneAgentEventTypes;
import org.silabsoft.runeagent.event.TransformerEvent;
import org.silabsoft.runeagent.listener.RuneAgentEventListener;

/**
 *
 * @author unsignedbyte
 */
public class AgentFrameGeneric extends javax.swing.JFrame implements RuneAgentEventListener, AgentFrame {

    /**
     * Creates new form AgentFrame
     */
    // Flag to track if Settings tab has been added
    private boolean settingsTabAdded = false;
    
    // References to panels for cross-communication
    private GenericOutStreamPanel outStreamPanel;
    private ScriptsPanel scriptsPanel;
    
    public AgentFrameGeneric() {
        initComponents();
        
        // Add Settings tab at the end
        jTabbedPane1.addTab("Settings", settingsPanel);
        settingsTabAdded = true;
    }
    
    /**
     * Sets the OutStreamPanel reference to access the script area
     */
    public void setOutStreamPanel(GenericOutStreamPanel panel) {
        this.outStreamPanel = panel;
        
        // Create and add Scripts tab if outStreamPanel is available
        if (outStreamPanel != null) {
            this.scriptsPanel = new ScriptsPanel(outStreamPanel.getScriptArea());
            
            // Add Scripts tab before Settings tab
            int settingsIndex = jTabbedPane1.indexOfTab("Settings");
            jTabbedPane1.insertTab("Scripts", null, this.scriptsPanel, "Manage saved scripts", settingsIndex);
            
            // Give the OutStreamPanel a reference to the ScriptsPanel
            this.outStreamPanel.setScriptsPanel(this.scriptsPanel);
        }
    }
    
    /**
     * Gets the ScriptsPanel reference
     */
    public ScriptsPanel getScriptsPanel() {
        return this.scriptsPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        settingsPanel = new javax.swing.JPanel();
        darkModeToggle = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RuneAgent-Revived Ver. "+RuneAgent.VERSION+" by glvckoma (GitHub)");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Rune Agent Log:"));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        darkModeToggle.setText("Enable Dark Mode");
        darkModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeToggleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPanelLayout = new javax.swing.GroupLayout(settingsPanel);
        settingsPanel.setLayout(settingsPanelLayout);
        settingsPanelLayout.setHorizontalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(darkModeToggle)
                .addContainerGap(607, Short.MAX_VALUE))
        );
        settingsPanelLayout.setVerticalGroup(
            settingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(darkModeToggle)
                .addContainerGap(328, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Startup", jPanel1);
        // Settings tab will be added at the end of initialization

        jMenu1.setText("GitHub");
        jMenu1.setToolTipText("Visit the GitHub repository");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
            try {
                desktop.browse(new URL(org.silabsoft.runeagent.RuneAgent.GITHUB_REPO).toURI());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void darkModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeToggleActionPerformed
        boolean isDarkMode = darkModeToggle.isSelected();
        
        // Use the ThemeManager to apply the theme
        String result = ThemeManager.applyTheme(this, isDarkMode);
        
        // Update button text based on current mode
        darkModeToggle.setText(isDarkMode ? "Enable Light Mode" : "Enable Dark Mode");
        
        // Directly apply syntax highlighting to any RSyntaxTextArea components
        if (scriptsPanel != null && scriptsPanel.getScriptArea() != null) {
            ThemeManager.applySyntaxHighlighting(scriptsPanel.getScriptArea(), isDarkMode);
        }
        
        // Apply to the outStreamPanel's script area if available
        if (outStreamPanel != null && outStreamPanel.getScriptArea() != null) {
            ThemeManager.applySyntaxHighlighting(outStreamPanel.getScriptArea(), isDarkMode);
        }
        
        logString(result);
    }//GEN-LAST:event_darkModeToggleActionPerformed
    
    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered
        // Change appearance on hover
        jMenu1.setForeground(java.awt.Color.BLUE);
        jMenu1.setFont(jMenu1.getFont().deriveFont(java.awt.Font.BOLD));
    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited
        // Restore original appearance
        jMenu1.setForeground(null); // Reset to default color
        jMenu1.setFont(jMenu1.getFont().deriveFont(java.awt.Font.PLAIN));
    }//GEN-LAST:event_jMenu1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentFrameGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentFrameGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentFrameGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentFrameGeneric.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentFrameGeneric().setVisible(true);
            }
        });
    }

    public void logString(String o) {
        Timestamp currentTimestamp = new java.sql.Timestamp(System.currentTimeMillis());
        jTextArea1.append("[" + currentTimestamp + "] - " + o + "\n");
        jTextArea1.setCaretPosition(jTextArea1.getText().length());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton darkModeToggle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel settingsPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onRuneAgentEvent(RuneAgentEvent e) {
        if (e.getType().equals(RuneAgentEventTypes.TRANSFORMER_EVENT)) {
            logString(((TransformerEvent) e).toString());
        } else {
            logString(e.getType() + " ");
        }
    }

    @Override
    public void addTab(Component component, String title) {
        if (settingsTabAdded) {
            // If Settings tab is already added, insert the new tab before it
            int settingsIndex = jTabbedPane1.indexOfTab("Settings");
            jTabbedPane1.insertTab(title, null, component, null, settingsIndex);
        } else {
            // If Settings tab is not yet added, add the tab normally
            jTabbedPane1.addTab(title, component);
        }
    }
}
