/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.silabsoft.runeagent.gui;

import java.awt.Color;
import java.awt.Component;
import java.lang.reflect.Method;
import javax.script.ScriptEngine;
import javax.script.ScriptException;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.silabsoft.runeagent.hook.ByteStreamMeta;

/**
 *
 * @author unsignedbyte
 */
public class GenericOutStreamPanel extends javax.swing.JPanel {

    protected final ScriptEngine engine; // Changed to protected
    protected Object outStreamObject; // Changed to protected
    protected boolean logging;
    private ScriptsPanel scriptsPanel; // Reference to the ScriptsPanel for updating

    public GenericOutStreamPanel(ScriptEngine engine) {
        initComponents();
        this.engine = engine;
        
        // Hide the Load Script button since we have the integrated script tab
        loadScriptButton.setVisible(false);
        
        // Style the log toggle button to make its state more visible
        updateLogToggleStyle();
    }
    
    /**
     * Updates the log toggle button style to make its state more visible
     */
    private void updateLogToggleStyle() {
        // Set custom colors for the toggle button
        logToggle.setFocusPainted(false);
        
        // Add an item listener to update the style when the toggle state changes
        logToggle.addItemListener(e -> {
            boolean isDarkMode = logToggle.getBackground().getRed() < 100;
            updateToggleButtonText(isDarkMode);
        });
        
        // Initial style update
        boolean isDarkMode = logToggle.getBackground().getRed() < 100;
        updateToggleButtonText(isDarkMode);
    }
    
    /**
     * Updates the toggle button text color based on the current state
     */
    private void updateToggleButtonText(boolean isDarkMode) {
        boolean isSelected = logToggle.isSelected();
        
        if (isSelected) {
            // Selected state - green text
            logToggle.setForeground(isDarkMode ? new Color(100, 255, 100) : new Color(0, 150, 0));
        } else {
            // Unselected state - red text
            logToggle.setForeground(isDarkMode ? new Color(255, 100, 100) : new Color(200, 0, 0));
        }
        
        // Keep the original text
        logToggle.setText("Log Incoming Packets");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputStreamLog = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        eventLog = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        clearLogButton = new javax.swing.JButton();
        clearEventLogButton = new javax.swing.JButton();
        saveScriptButton = new javax.swing.JButton();
        loadScriptButton = new javax.swing.JButton();
        logToggle = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        rTextScrollPane2 = new org.fife.ui.rtextarea.RTextScrollPane(scriptArea);
        scriptArea = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea(5,20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Incoming Packets"));

        outputStreamLog.setColumns(20);
        outputStreamLog.setRows(5);
        jScrollPane1.setViewportView(outputStreamLog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Event Log:"));

        eventLog.setColumns(20);
        eventLog.setRows(5);
        jScrollPane2.setViewportView(eventLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        jButton3.setText("Execute Script");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        clearLogButton.setText("Clear Packets");
        clearLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButtonActionPerformed(evt);
            }
        });

        clearEventLogButton.setText("Clear Event Log");
        clearEventLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEventLogButtonActionPerformed(evt);
            }
        });

        saveScriptButton.setText("Save Script");
        saveScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveScriptButtonActionPerformed(evt);
            }
        });

        loadScriptButton.setText("Load Script");
        loadScriptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadScriptButtonActionPerformed(evt);
            }
        });

        logToggle.setSelected(true);
        logToggle.setText("Log Incoming Packets");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(clearLogButton)
                    .addComponent(clearEventLogButton)
                    .addComponent(saveScriptButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logToggle)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveScriptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearLogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearEventLogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logToggle)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Quick Insert"));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Script:"));

        scriptArea.setColumns(20);
        scriptArea.setRows(5);
        scriptArea.setCodeFoldingEnabled(true);
        scriptArea.setMarginLineEnabled(true);
        scriptArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVASCRIPT);
        rTextScrollPane2.setViewportView(scriptArea);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rTextScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rTextScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            engine.eval(scriptArea.getText());
        } catch (ScriptException ex) {
            logEvent(eventLog, ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            int index = jList1.locationToIndex(evt.getPoint());
            Object o = jList1.getModel().getElementAt(index);
            if (o != null) {
                if (o instanceof ByteStreamMeta) {
                    ByteStreamMeta bsm = (ByteStreamMeta) o;
                    scriptArea.insert("stream." + bsm.methodName() + "(" + bsm.parameters() + ");\n", scriptArea.getCaretPosition());
                }
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void clearLogButtonActionPerformed(java.awt.event.ActionEvent evt) {
        outputStreamLog.setText("");
    }
    
    private void saveScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String scriptName = javax.swing.JOptionPane.showInputDialog(this, 
                "Enter script name:", 
                "Save Script", 
                javax.swing.JOptionPane.PLAIN_MESSAGE);
        
        if (scriptName != null && !scriptName.trim().isEmpty()) {
            // Add .js extension if not present
            if (!scriptName.toLowerCase().endsWith(".js")) {
                scriptName += ".js";
            }
            
            java.io.File scriptFile = new java.io.File("scripts" + java.io.File.separator + scriptName);
            
            // Check if file exists and confirm overwrite
            if (scriptFile.exists()) {
                int result = javax.swing.JOptionPane.showConfirmDialog(this, 
                        "Script already exists. Overwrite?", 
                        "Confirm Overwrite", 
                        javax.swing.JOptionPane.YES_NO_OPTION);
                
                if (result != javax.swing.JOptionPane.YES_OPTION) {
                    return;
                }
            }
            
            try (java.io.FileWriter writer = new java.io.FileWriter(scriptFile)) {
                writer.write(scriptArea.getText());
                logEvent(eventLog, "Script saved to: " + scriptFile.getAbsolutePath());
                
                // Refresh the scripts list in the Scripts tab
                if (scriptsPanel != null) {
                    scriptsPanel.refreshScriptsList();
                }
            } catch (java.io.IOException e) {
                logEvent(eventLog, "Error saving script: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }
    
    private void loadScriptButtonActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Load Script");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("JavaScript Files (*.js)", "js"));
        
        if (fileChooser.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            
            try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(file))) {
                StringBuilder content = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    content.append(line).append("\n");
                }
                scriptArea.setText(content.toString());
                logEvent(eventLog, "Script loaded from: " + file.getAbsolutePath());
            } catch (java.io.IOException e) {
                logEvent(eventLog, "Error loading script: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }
    
    private void clearEventLogButtonActionPerformed(java.awt.event.ActionEvent evt) {
        eventLog.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextArea eventLog;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton clearLogButton;
    private javax.swing.JButton clearEventLogButton;
    private javax.swing.JButton loadScriptButton;
    private javax.swing.JButton saveScriptButton;
    protected javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton logToggle;
    private javax.swing.JTextArea outputStreamLog;
    private org.fife.ui.rtextarea.RTextScrollPane rTextScrollPane2;
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea scriptArea;
    // End of variables declaration//GEN-END:variables

    public void addOutStreamObject(Object o) {
        this.outStreamObject = o;
        this.engine.put("stream", o);
        DefaultListModel model = new DefaultListModel();
        for (Class i : o.getClass().getInterfaces()) {
            for (Method m : i.getMethods()) {
                ByteStreamMeta bsm = m.getAnnotation(ByteStreamMeta.class);
                if (bsm != null) {
                    model.addElement(bsm);
                }
            }
        }
        jList1.setModel(model);
        jList1.setCellRenderer(new ByteStreamMetaJListCellRenderer());
        logEvent(eventLog, "Outstream object set.");
    }

    public void logEvent(JTextArea area, String o) {
        if (area.equals(outputStreamLog) && !logToggle.isSelected()) {
            return;
        }
        area.append(o + "\n");
        area.setCaretPosition(area.getText().length());
    }

    public Component getOutStreamLogComponent() {
        return outputStreamLog;
    }
    
    /**
     * Returns the script text area for use by the ScriptsPanel
     */
    public RSyntaxTextArea getScriptArea() {
        return scriptArea;
    }
    
    /**
     * Sets the ScriptsPanel reference for updating the scripts list
     */
    public void setScriptsPanel(ScriptsPanel panel) {
        this.scriptsPanel = panel;
    }
}
